Repository Korea-Certified-Store/AOS, pull requests merged in 2024-01, with the labels that each got.

#4 Naver Map Compose를 적용하고 메인 지도 화면을 표시한다
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/res/values/themes.xml
  gradle.properties
  gradle/libs.versions.toml
  presentation/build.gradle.kts
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/example/presentation/ui/MainActivity.kt
  presentation/src/main/java/com/example/presentation/ui/theme/Theme.kt
  presentation/src/main/res/values/themes.xml
  settings.gradle.kts
Labels: ✨ Feature, 📱 Layout

#7 해당 가게의 상세정보를 담은 Bottom Sheet를 보여준다
  app/build.gradle.kts
  app/src/androidTest/java/com/example/android_kcs/ExampleInstrumentedTest.kt
  app/src/main/AndroidManifest.xml
  data/build.gradle.kts
  data/src/main/dto/dummy.txt
  data/src/main/repository/dummy.txt
  data/src/main/source/remote/api/dummy.txt
  domain/src/main/java/com/example/domain/model/dummy.txt
  domain/src/main/java/com/example/domain/repository/dummy.txt
  domain/src/main/java/com/example/domain/usecase/dummy.txt
  gradle/libs.versions.toml
  presentation/build.gradle.kts
  presentation/src/main/java/com/example/presentation/model/Coordinate.kt
  presentation/src/main/java/com/example/presentation/model/StoreInfo.kt
  presentation/src/main/java/com/example/presentation/model/StoreType.kt
  presentation/src/main/java/com/example/presentation/model/dummy.txt
  presentation/src/main/java/com/example/presentation/ui/MainActivity.kt
  presentation/src/main/java/com/example/presentation/ui/MainScreen.kt
  presentation/src/main/java/com/example/presentation/ui/theme/Color.kt
  presentation/src/main/res/drawable/call.png
  presentation/src/main/res/drawable/great_store_pin.png
  presentation/src/main/res/drawable/ic_launcher_background.xml
  presentation/src/main/res/drawable/ic_launcher_foreground.xml
  presentation/src/main/res/drawable/kind_store_pin.png
  presentation/src/main/res/drawable/safe_store_pin.png
  presentation/src/main/res/drawable/store_example.png
Labels: ✨ Feature, 📱 Layout

#8 해당 가게의 상세정보를 담은 Bottom Sheet를 보여준다 - 피드백 반영 & bottom sheet 디자인 변경 & 마커 클릭시 마커 변경
  app/src/main/res/values/themes.xml
  presentation/src/main/java/com/example/presentation/model/StoreInfo.kt
  presentation/src/main/java/com/example/presentation/model/StoreType.kt
  presentation/src/main/java/com/example/presentation/model/dummy.txt
  presentation/src/main/java/com/example/presentation/ui/MainActivity.kt
  presentation/src/main/java/com/example/presentation/ui/MainScreen.kt
  presentation/src/main/java/com/example/presentation/ui/theme/Color.kt
  presentation/src/main/res/drawable/call.png
  presentation/src/main/res/drawable/call.xml
  presentation/src/main/res/drawable/clicked_great_store_pin.xml
  presentation/src/main/res/drawable/clicked_kind_store_pin.xml
  presentation/src/main/res/drawable/clicked_safe_store_pin.xml
  presentation/src/main/res/drawable/great_store_pin.png
  presentation/src/main/res/drawable/great_store_pin.xml
  presentation/src/main/res/drawable/kind_store_pin.png
  presentation/src/main/res/drawable/kind_store_pin.xml
  presentation/src/main/res/drawable/safe_store_pin.png
  presentation/src/main/res/drawable/safe_store_pin.xml
  presentation/src/main/res/drawable/store_example.png
  presentation/ui/dummy.txt
Labels: 📱 Layout

#11 전화 버튼을 누르면 전화 다이얼로그를 띄운다 (전화 걸기, 전화번호 저장, 클립보드에 복사)
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/example/presentation/model/Contact.kt
  presentation/src/main/java/com/example/presentation/model/StoreType.kt
  presentation/src/main/java/com/example/presentation/ui/CallScreen.kt
  presentation/src/main/java/com/example/presentation/ui/MainActivity.kt
  presentation/src/main/java/com/example/presentation/ui/MainScreen.kt
  presentation/src/main/res/values/strings.xml
Labels: ✨ Feature, 📱 Layout

#15 위치 변동 여부를 확인 후 변했다면 재검색 버튼을 띄운다
  presentation/src/main/java/com/example/presentation/model/StoreType.kt
  presentation/src/main/java/com/example/presentation/ui/CallScreen.kt
  presentation/src/main/java/com/example/presentation/ui/MainScreen.kt
  presentation/src/main/java/com/example/presentation/ui/MainUtils.kt
  presentation/src/main/java/com/example/presentation/ui/SearchOnCurrentMapScreen.kt
  presentation/src/main/java/com/example/presentation/ui/StoreSummaryScreen.kt
  presentation/src/main/java/com/example/presentation/ui/theme/Color.kt
  presentation/src/main/java/com/example/presentation/ui/theme/Theme.kt
  presentation/src/main/java/com/example/presentation/ui/theme/Type.kt
  presentation/src/main/res/drawable/call.xml
  presentation/src/main/res/drawable/search.xml
  presentation/src/main/res/font/roboto_black.ttf
  presentation/src/main/res/font/roboto_blackitalic.ttf
  presentation/src/main/res/font/roboto_bold.ttf
  presentation/src/main/res/font/roboto_bolditalic.ttf
  presentation/src/main/res/font/roboto_italic.ttf
  presentation/src/main/res/font/roboto_light.ttf
  presentation/src/main/res/font/roboto_lightitalic.ttf
  presentation/src/main/res/font/roboto_medium.ttf
  presentation/src/main/res/font/roboto_mediumitalic.ttf
  presentation/src/main/res/font/roboto_regular.ttf
  presentation/src/main/res/font/roboto_thin.ttf
  presentation/src/main/res/font/roboto_thinitalic.ttf
  presentation/src/main/res/values/strings.xml
Labels: ✨ Feature, 📱 Layout

#18 현재 카메라 좌표를 기준으로 가게의 데이터를 받아와 뷰에 표시한다
  .gitignore
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/android_kcs/AndroidKCSApp.kt
  app/src/main/java/com/example/android_kcs/di/ApiModule.kt
  app/src/main/java/com/example/android_kcs/di/DataSourceModule.kt
  app/src/main/java/com/example/android_kcs/di/Extension.kt
  app/src/main/java/com/example/android_kcs/di/NetworkModule.kt
  app/src/main/java/com/example/android_kcs/di/RepositoryModule.kt
  app/src/main/java/com/example/android_kcs/di/UseCaseModule.kt
  build.gradle.kts
  data/build.gradle.kts
  data/src/main/dto/dummy.txt
  data/src/main/java/com/example/data/dto/response/BaseResponse.kt
  data/src/main/java/com/example/data/dto/response/CoordinateDto.kt
  data/src/main/java/com/example/data/dto/response/OpeningHoursDto.kt
  data/src/main/java/com/example/data/dto/response/ResponseStoreDetailDto.kt
  data/src/main/java/com/example/data/dto/response/TimeInfoData.kt
  data/src/main/java/com/example/data/repository/StoreDetailRepositoryImpl.kt
  data/src/main/java/com/example/data/source/StoreDetailDataSource.kt
  data/src/main/java/com/example/data/source/remote/StoreDetailSourceImpl.kt
  data/src/main/java/com/example/data/source/remote/api/StoreDetailApiService.kt
  data/src/main/repository/dummy.txt
  data/src/main/source/remote/api/dummy.txt
  domain/build.gradle.kts
  domain/src/main/java/com/example/domain/model/Coordinate.kt
  domain/src/main/java/com/example/domain/model/OpeningHours.kt
  domain/src/main/java/com/example/domain/model/StoreDetail.kt
  domain/src/main/java/com/example/domain/model/TimeInfo.kt
  domain/src/main/java/com/example/domain/model/dummy.txt
  domain/src/main/java/com/example/domain/repository/StoreDetailRepository.kt
  domain/src/main/java/com/example/domain/repository/dummy.txt
  domain/src/main/java/com/example/domain/usecase/GetStoreDetailUseCase.kt
  domain/src/main/java/com/example/domain/usecase/dummy.txt
  gradle/libs.versions.toml
  presentation/build.gradle.kts
  presentation/src/main/java/com/example/presentation/mapper/StoreDetailMapper.kt
  presentation/src/main/java/com/example/presentation/model/CoordinateModel.kt
  presentation/src/main/java/com/example/presentation/model/StoreDetailModel.kt
  presentation/src/main/java/com/example/presentation/model/StoreInfo.kt
  presentation/src/main/java/com/example/presentation/ui/MainActivity.kt
  presentation/src/main/java/com/example/presentation/ui/MainScreen.kt
  presentation/src/main/java/com/example/presentation/ui/MainViewModel.kt
  presentation/src/main/java/com/example/presentation/ui/StoreSummaryScreen.kt
  presentation/src/main/java/com/example/presentation/ui/UiState.kt
Labels: ✨ Feature, 📱 Layout

#17 필터 버튼의 활성화/비활성화 상태를 표시한다
  presentation/src/main/java/com/example/presentation/model/StoreType.kt
  presentation/src/main/java/com/example/presentation/ui/FilterScreen.kt
  presentation/src/main/java/com/example/presentation/ui/MainScreen.kt
  presentation/src/main/java/com/example/presentation/ui/SearchOnCurrentMapScreen.kt
Labels: 📱 Layout

#20 bug fix
  data/src/main/java/com/example/data/dto/response/CoordinateDto.kt
  data/src/main/java/com/example/data/dto/response/OpeningHoursDto.kt
  data/src/main/java/com/example/data/dto/response/ResponseStoreDetailDto.kt
  data/src/main/java/com/example/data/dto/response/TimeInfoData.kt
  data/src/main/java/com/example/data/repository/StoreDetailRepositoryImpl.kt
  data/src/main/java/com/example/data/source/StoreDetailDataSource.kt
  data/src/main/java/com/example/data/source/remote/StoreDetailSourceImpl.kt
  domain/src/main/java/com/example/domain/MyClass.kt
  domain/src/main/java/com/example/domain/model/CoordinateModel.kt
  domain/src/main/java/com/example/domain/model/OpeningHoursModel.kt
  domain/src/main/java/com/example/domain/model/StoreDetailModel.kt
  domain/src/main/java/com/example/domain/model/TimeInfoModel.kt
  domain/src/main/java/com/example/domain/repository/StoreDetailRepository.kt
  domain/src/main/java/com/example/domain/usecase/GetStoreDetailUseCase.kt
  presentation/src/main/java/com/example/presentation/mapper/StoreDetailMapper.kt
  presentation/src/main/java/com/example/presentation/model/Coordinate.kt
  presentation/src/main/java/com/example/presentation/model/OpeningHours.kt
  presentation/src/main/java/com/example/presentation/model/StoreDetail.kt
  presentation/src/main/java/com/example/presentation/model/StoreDetailModel.kt
  presentation/src/main/java/com/example/presentation/model/TimeInfo.kt
  presentation/src/main/java/com/example/presentation/ui/MainScreen.kt
  presentation/src/main/java/com/example/presentation/ui/MainViewModel.kt
  presentation/src/main/java/com/example/presentation/ui/StoreSummaryScreen.kt
Labels: 🛠️ Fix

#23 재검색 버튼이 클릭되면 viewModel 변수를 초기화하고 api 통신 후 마커를 표시한다
  presentation/src/main/java/com/example/presentation/model/ScreenCoordinate.kt
  presentation/src/main/java/com/example/presentation/ui/MainScreen.kt
  presentation/src/main/java/com/example/presentation/ui/map/InitLocationButton.kt
  presentation/src/main/java/com/example/presentation/ui/map/NaverMapScreen.kt
  presentation/src/main/java/com/example/presentation/util/MainConstants.kt
Labels: ✨ Feature

#26 권한 여부에 따른 현위치 버튼 동작 & 스낵바 구현
  .gitignore
  app/src/main/AndroidManifest.xml
  presentation/src/main/java/com/example/presentation/model/LocationTrackingButton.kt
  presentation/src/main/java/com/example/presentation/ui/MainActivity.kt
  presentation/src/main/java/com/example/presentation/ui/MainScreen.kt
  presentation/src/main/java/com/example/presentation/ui/MainViewModel.kt
  presentation/src/main/java/com/example/presentation/ui/map/InitLocationButton.kt
  presentation/src/main/java/com/example/presentation/ui/map/LocationPermissionRequest.kt
  presentation/src/main/java/com/example/presentation/ui/map/LocationPermissionScreen.kt
  presentation/src/main/java/com/example/presentation/ui/map/NaverMapScreen.kt
Labels: ✨ Feature, 📱 Layout

#29 클릭된 필터 버튼에 해당하는 마커를 확인할 수 있다
  presentation/src/main/java/com/example/presentation/mapper/StoreDetailMapper.kt
  presentation/src/main/java/com/example/presentation/ui/MainScreen.kt
  presentation/src/main/java/com/example/presentation/ui/MainViewModel.kt
  presentation/src/main/java/com/example/presentation/ui/map/FilterScreen.kt
  presentation/src/main/java/com/example/presentation/ui/map/NaverMapScreen.kt
  presentation/src/main/java/com/example/presentation/ui/map/StoreMarker.kt
  presentation/src/main/java/com/example/presentation/util/MainConstants.kt
Labels: ✨ Feature, 📱 Layout

#32 UI 레이어 리팩토링
  app/build.gradle.kts
  presentation/src/main/java/com/example/presentation/ui/MainActivity.kt
  presentation/src/main/java/com/example/presentation/ui/MainScreen.kt
  presentation/src/main/java/com/example/presentation/ui/map/MapViewModel.kt
  presentation/src/main/java/com/example/presentation/ui/map/NaverMapScreen.kt
  presentation/src/main/java/com/example/presentation/ui/map/call/StoreCallDialog.kt
  presentation/src/main/java/com/example/presentation/ui/map/detail/dummy.txt
  presentation/src/main/java/com/example/presentation/ui/map/filter/FilterComponent.kt
  presentation/src/main/java/com/example/presentation/ui/map/location/CurrentLocationComponent.kt
  presentation/src/main/java/com/example/presentation/ui/map/location/LocationPermissionRequest.kt
  presentation/src/main/java/com/example/presentation/ui/map/location/LocationPermissionScreen.kt
  presentation/src/main/java/com/example/presentation/ui/map/marker/StoreMarker.kt
  presentation/src/main/java/com/example/presentation/ui/map/reload/ReloadButton.kt
  presentation/src/main/java/com/example/presentation/ui/map/summary/StoreSummaryBottomSheet.kt
  presentation/src/main/java/com/example/presentation/util/MainConstants.kt
Labels: 👷‍♂️ Refactor

#37 Bottom Sheet의 요약 정보 ↔ 상세 정보 상태를 swipe로 변경할 수 있다
  presentation/src/main/java/com/example/presentation/model/ExpandedType.kt
  presentation/src/main/java/com/example/presentation/ui/MainScreen.kt
  presentation/src/main/java/com/example/presentation/ui/map/NaverMapScreen.kt
  presentation/src/main/java/com/example/presentation/ui/map/reload/ReloadButton.kt
  presentation/src/main/java/com/example/presentation/ui/map/summary/StoreSummaryBottomSheet.kt
  presentation/src/main/java/com/example/presentation/ui/map/summary/StoreSummaryComponent.kt
  presentation/src/main/java/com/example/presentation/ui/theme/Color.kt
  presentation/src/main/java/com/example/presentation/util/MainConstants.kt
  presentation/src/main/res/drawable/call.xml
Labels: ✨ Feature, 📱 Layout

#39 BottomSheet Logic 수정
  presentation/src/main/java/com/example/presentation/model/ExpandedType.kt
  presentation/src/main/java/com/example/presentation/ui/MainScreen.kt
  presentation/src/main/java/com/example/presentation/ui/map/summary/DimScreen.kt
  presentation/src/main/java/com/example/presentation/ui/map/summary/StoreSummaryBottomSheet.kt
  presentation/src/main/java/com/example/presentation/ui/theme/Color.kt
  presentation/src/main/java/com/example/presentation/util/MainConstants.kt
Labels: ✨ Feature, 📱 Layout

#42 Network Exception 처리
  domain/src/main/java/com/example/domain/usecase/GetStoreDetailUseCase.kt
  domain/src/main/java/com/example/domain/util/Resource.kt
  gradle/libs.versions.toml
  presentation/build.gradle.kts
  presentation/src/main/java/com/example/presentation/ui/MainScreen.kt
  presentation/src/main/java/com/example/presentation/ui/map/MapViewModel.kt
  presentation/src/main/java/com/example/presentation/ui/map/NaverMapScreen.kt
  presentation/src/main/java/com/example/presentation/ui/map/reload/ReloadButton.kt
  presentation/src/main/java/com/example/presentation/util/UiState.kt
Labels: ✨ Feature, 📱 Layout

#45 Firebase Analytics 및 Crashlytics 적용
  app/build.gradle.kts
  build.gradle.kts
  gradle/libs.versions.toml
  presentation/build.gradle.kts
  presentation/src/main/AndroidManifest.xml
Labels: ✨ Feature

#46 BottomSheet 요약, 상세 전환 및 Dim 애니메이션 구현
  presentation/src/main/java/com/example/presentation/model/ExpandedType.kt
  presentation/src/main/java/com/example/presentation/ui/MainScreen.kt
  presentation/src/main/java/com/example/presentation/ui/map/NaverMapScreen.kt
  presentation/src/main/java/com/example/presentation/ui/map/detail/StoreDetailComponent.kt
  presentation/src/main/java/com/example/presentation/ui/map/reload/ReloadButton.kt
  presentation/src/main/java/com/example/presentation/ui/map/summary/DimScreen.kt
  presentation/src/main/java/com/example/presentation/ui/map/summary/StoreSummaryBottomSheet.kt
  presentation/src/main/java/com/example/presentation/util/MainConstants.kt
Labels: 📱 Layout
