Repository Korea-Certified-Store/AOS, pull requests merged in 2024-02, with the labels that each got.

#48 더보기 버튼 구현을 위한 가게 정보 API Response 수정
  data/src/main/java/com/example/data/repository/StoreDetailRepositoryImpl.kt
  data/src/main/java/com/example/data/source/StoreDetailDataSource.kt
  data/src/main/java/com/example/data/source/remote/StoreDetailSourceImpl.kt
  data/src/main/java/com/example/data/source/remote/api/StoreDetailApiService.kt
  domain/src/main/java/com/example/domain/repository/StoreDetailRepository.kt
  domain/src/main/java/com/example/domain/usecase/GetStoreDetailUseCase.kt
  presentation/src/main/java/com/example/presentation/ui/map/MapViewModel.kt
  presentation/src/main/java/com/example/presentation/ui/map/NaverMapScreen.kt
Labels: ✨ Feature

#50 가게 리스트 Layout 구현
  presentation/src/main/java/com/example/presentation/ui/component/ChipComponent.kt
  presentation/src/main/java/com/example/presentation/ui/component/ImageComponent.kt
  presentation/src/main/java/com/example/presentation/ui/component/TextComponent.kt
  presentation/src/main/java/com/example/presentation/ui/map/detail/StoreDetailComponent.kt
  presentation/src/main/java/com/example/presentation/ui/map/list/StoreListComponent.kt
  presentation/src/main/java/com/example/presentation/ui/map/summary/StoreSummaryComponent.kt
  presentation/src/main/java/com/example/presentation/ui/theme/Color.kt
  presentation/src/main/java/com/example/presentation/util/MainConstants.kt
Labels: 📱 Layout

#53 가게 리스트를 담은 BottomSheet를 보여준다
  presentation/src/main/java/com/example/presentation/ui/MainScreen.kt
  presentation/src/main/java/com/example/presentation/ui/component/BottomSheetHandleComponent.kt
  presentation/src/main/java/com/example/presentation/ui/map/NaverMapScreen.kt
  presentation/src/main/java/com/example/presentation/ui/map/list/StoreListBottomSheet.kt
  presentation/src/main/java/com/example/presentation/ui/map/list/StoreListComponent.kt
  presentation/src/main/java/com/example/presentation/ui/map/reload/ReloadButton.kt
  presentation/src/main/java/com/example/presentation/ui/map/summary/StoreSummaryBottomSheet.kt
  presentation/src/main/java/com/example/presentation/util/MainConstants.kt
  presentation/src/main/res/values/strings.xml
Labels: ✨ Feature, 📱 Layout

#54 온보딩 Screen 구현
  presentation/src/main/java/com/example/presentation/ui/MainActivity.kt
  presentation/src/main/java/com/example/presentation/ui/MainScreen.kt
  presentation/src/main/java/com/example/presentation/ui/onboarding/OnboardingPageContent.kt
  presentation/src/main/java/com/example/presentation/ui/onboarding/OnboardingScreen.kt
  presentation/src/main/java/com/example/presentation/ui/theme/Color.kt
  presentation/src/main/res/drawable/onboarding_fifth.png
  presentation/src/main/res/drawable/onboarding_first.png
  presentation/src/main/res/drawable/onboarding_fourth.png
  presentation/src/main/res/drawable/onboarding_second.png
  presentation/src/main/res/drawable/onboarding_third.png
Labels: 📱 Layout

#56 더보기 버튼 구현
  presentation/src/main/java/com/example/presentation/ui/MainActivity.kt
  presentation/src/main/java/com/example/presentation/ui/MainScreen.kt
  presentation/src/main/java/com/example/presentation/ui/map/MapViewModel.kt
  presentation/src/main/java/com/example/presentation/ui/map/NaverMapScreen.kt
  presentation/src/main/java/com/example/presentation/ui/map/list/StoreListBottomSheet.kt
  presentation/src/main/java/com/example/presentation/ui/map/reload/ReloadButton.kt
  presentation/src/main/java/com/example/presentation/ui/map/reload/ReloadOrShowMoreButton.kt
  presentation/src/main/java/com/example/presentation/ui/map/reload/ShowMoreButton.kt
  presentation/src/main/java/com/example/presentation/ui/onboarding/OnboardingScreen.kt
  presentation/src/main/java/com/example/presentation/util/MainConstants.kt
  presentation/src/main/res/values/strings.xml
Labels: ✨ Feature, 📱 Layout

#58 2차 출시의 버그 수정
  domain/src/main/java/com/example/domain/usecase/GetStoreDetailUseCase.kt
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/example/presentation/ui/MainActivity.kt
  presentation/src/main/java/com/example/presentation/ui/MainScreen.kt
  presentation/src/main/java/com/example/presentation/ui/map/NaverMapScreen.kt
  presentation/src/main/java/com/example/presentation/ui/splash/SplashAnimation.kt
  presentation/src/main/java/com/example/presentation/ui/splash/SplashScreen.kt
  presentation/src/main/res/drawable/splash_1.xml
  presentation/src/main/res/drawable/splash_2.xml
  presentation/src/main/res/drawable/splash_3.xml
  presentation/src/main/res/drawable/splash_4.xml
  presentation/src/main/res/drawable/splash_5.xml
  presentation/src/main/res/drawable/splash_6.xml
Labels: 🛠️ Fix

#59 재검색 버튼 PR 코드리뷰 반영 수정
  domain/src/main/java/com/example/domain/model/map/ShowMoreCount.kt
  presentation/src/main/java/com/example/presentation/ui/MainScreen.kt
  presentation/src/main/java/com/example/presentation/ui/map/MapViewModel.kt
  presentation/src/main/java/com/example/presentation/ui/map/NaverMapScreen.kt
  presentation/src/main/java/com/example/presentation/ui/map/reload/ReloadButton.kt
  presentation/src/main/java/com/example/presentation/ui/map/reload/ReloadOrShowMoreButton.kt
  presentation/src/main/java/com/example/presentation/ui/map/reload/ShowMoreButton.kt
Labels: 🛠️ Fix

#65 운영 개발 버전 분리
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/res/values/strings.xml
Labels: 🧱 Build

#66 현위치 이동 및 가게 초기화 로직 수정
  presentation/src/main/java/com/example/presentation/ui/MainScreen.kt
  presentation/src/main/java/com/example/presentation/ui/map/MapViewModel.kt
  presentation/src/main/java/com/example/presentation/ui/map/NaverMapScreen.kt
  presentation/src/main/java/com/example/presentation/util/MainConstants.kt
Labels: 🛠️ Fix

#71 Hotfix 3.1
  README.md
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/res/values/strings.xml
  presentation/src/main/java/com/example/presentation/ui/MainScreen.kt
  presentation/src/main/java/com/example/presentation/ui/map/MapViewModel.kt
  presentation/src/main/java/com/example/presentation/ui/map/NaverMapScreen.kt
  presentation/src/main/java/com/example/presentation/ui/map/summary/StoreSummaryBottomSheet.kt
  presentation/src/main/java/com/example/presentation/util/MainConstants.kt
Labels: 🛠️ Fix, 🎯 Release

#75 가게가 없을 경우 안내 Toast 구현
  domain/src/main/java/com/example/domain/usecase/ErrorMessage.kt
  domain/src/main/java/com/example/domain/usecase/GetStoreDetailUseCase.kt
  domain/src/main/java/com/example/domain/usecase/SearchStoreUseCase.kt
  presentation/src/main/java/com/example/presentation/ui/map/MapViewModel.kt
  presentation/src/main/java/com/example/presentation/ui/map/NaverMapScreen.kt
Labels: ✨ Feature

#76 검색 TextField와 검색 Screen Layout 및 동작 구현
  gradle/libs.versions.toml
  presentation/build.gradle.kts
  presentation/src/main/java/com/example/presentation/ui/MainActivity.kt
  presentation/src/main/java/com/example/presentation/ui/MainScreen.kt
  presentation/src/main/java/com/example/presentation/ui/component/ChipComponent.kt
  presentation/src/main/java/com/example/presentation/ui/component/TextComponent.kt
  presentation/src/main/java/com/example/presentation/ui/map/NaverMapScreen.kt
  presentation/src/main/java/com/example/presentation/ui/map/filter/FilterComponent.kt
  presentation/src/main/java/com/example/presentation/ui/map/reload/ReloadButton.kt
  presentation/src/main/java/com/example/presentation/ui/map/reload/ShowMoreButton.kt
  presentation/src/main/java/com/example/presentation/ui/map/summary/StoreSummaryComponent.kt
  presentation/src/main/java/com/example/presentation/ui/navigation/Screen.kt
  presentation/src/main/java/com/example/presentation/ui/search/SearchScreen.kt
  presentation/src/main/java/com/example/presentation/ui/search/StoreSearchComponent.kt
  presentation/src/main/java/com/example/presentation/ui/theme/Color.kt
  presentation/src/main/java/com/example/presentation/util/MainConstants.kt
  presentation/src/main/res/drawable/delete.xml
  presentation/src/main/res/drawable/reload.xml
  presentation/src/main/res/drawable/search.xml
  presentation/src/main/res/values/strings.xml
Labels: 📱 Layout

#78 검색어 DataBase에 저장 및 삭제
  app/build.gradle.kts
  app/src/main/java/com/example/android_kcs/di/DataSourceModule.kt
  app/src/main/java/com/example/android_kcs/di/DatabaseModule.kt
  app/src/main/java/com/example/android_kcs/di/RepositoryModule.kt
  app/src/main/java/com/example/android_kcs/di/UseCaseModule.kt
  data/build.gradle.kts
  data/src/main/java/com/example/data/repository/SearchWordRepositoryImpl.kt
  data/src/main/java/com/example/data/source/SearchWordDataSource.kt
  data/src/main/java/com/example/data/source/local/SearchWordDataSourceImpl.kt
  data/src/main/java/com/example/data/source/local/dao/SearchWordDao.kt
  data/src/main/java/com/example/data/source/local/database/SearchWordDatabase.kt
  data/src/main/java/com/example/data/source/local/entity/SearchWordEntity.kt
  domain/src/main/java/com/example/domain/model/search/SearchWord.kt
  domain/src/main/java/com/example/domain/repository/SearchWordRepository.kt
  domain/src/main/java/com/example/domain/usecase/DeleteAllSearchWordsUseCase.kt
  domain/src/main/java/com/example/domain/usecase/DeleteSearchWordByIdUseCase.kt
  domain/src/main/java/com/example/domain/usecase/GetRecentSearchWordUseCase.kt
  domain/src/main/java/com/example/domain/usecase/GetStoreDetailUseCase.kt
  domain/src/main/java/com/example/domain/usecase/InsertSearchWordUseCase.kt
  domain/src/main/java/com/example/domain/usecase/SearchStoreUseCase.kt
  domain/src/main/java/com/example/domain/util/ErrorMessage.kt
  domain/src/main/java/com/example/domain/util/GetOperationTime.kt
  gradle/libs.versions.toml
  presentation/src/main/java/com/example/presentation/ui/map/NaverMapScreen.kt
  presentation/src/main/java/com/example/presentation/ui/search/SearchScreen.kt
  presentation/src/main/java/com/example/presentation/ui/search/SearchViewModel.kt
Labels: ✨ Feature

#84 hotfix Splash Animation 오류 해결
  presentation/src/main/java/com/example/presentation/ui/splash/SplashAnimation.kt
Labels: 🛠️ Fix

#81 검색 결과에 따른 지도 로직 구현
  presentation/build.gradle.kts
  presentation/src/main/java/com/example/presentation/model/Coordinate.kt
  presentation/src/main/java/com/example/presentation/ui/InitScreen.kt
  presentation/src/main/java/com/example/presentation/ui/MainActivity.kt
  presentation/src/main/java/com/example/presentation/ui/MainScreen.kt
  presentation/src/main/java/com/example/presentation/ui/map/MapViewModel.kt
  presentation/src/main/java/com/example/presentation/ui/map/NaverMapScreen.kt
  presentation/src/main/java/com/example/presentation/ui/map/detail/StoreDetailComponent.kt
  presentation/src/main/java/com/example/presentation/ui/map/list/StoreListBottomSheet.kt
  presentation/src/main/java/com/example/presentation/ui/map/reload/ReloadButton.kt
  presentation/src/main/java/com/example/presentation/ui/map/reload/ReloadOrShowMoreButton.kt
  presentation/src/main/java/com/example/presentation/ui/map/reload/ShowMoreButton.kt
  presentation/src/main/java/com/example/presentation/ui/search/SearchScreen.kt
  presentation/src/main/java/com/example/presentation/ui/search/StoreSearchComponent.kt
  presentation/src/main/java/com/example/presentation/util/MainConstants.kt
  presentation/src/main/java/com/example/presentation/util/MapScreenType.kt
Labels: 📱 Layout

#85 검색 로직과 layout 연결
  presentation/src/main/java/com/example/presentation/ui/MainActivity.kt
  presentation/src/main/java/com/example/presentation/ui/MainScreen.kt
  presentation/src/main/java/com/example/presentation/ui/map/MapViewModel.kt
  presentation/src/main/java/com/example/presentation/ui/map/NaverMapScreen.kt
  presentation/src/main/java/com/example/presentation/ui/search/SearchScreen.kt
Labels: ✨ Feature

#89 현위치에서 키워드로 재검색, 검색 시 필터 초기화
  presentation/src/main/java/com/example/presentation/ui/InitScreen.kt
  presentation/src/main/java/com/example/presentation/ui/MainActivity.kt
  presentation/src/main/java/com/example/presentation/ui/MainScreen.kt
  presentation/src/main/java/com/example/presentation/ui/map/MapViewModel.kt
  presentation/src/main/java/com/example/presentation/ui/map/NaverMapScreen.kt
  presentation/src/main/java/com/example/presentation/ui/map/filter/FilterComponent.kt
  presentation/src/main/java/com/example/presentation/ui/map/filter/FilterViewModel.kt
  presentation/src/main/java/com/example/presentation/ui/map/list/StoreListBottomSheet.kt
  presentation/src/main/java/com/example/presentation/ui/search/ReSearchComponent.kt
  presentation/src/main/java/com/example/presentation/ui/search/SearchScreen.kt
  presentation/src/main/java/com/example/presentation/ui/search/StoreSearchComponent.kt
  presentation/src/main/res/values/strings.xml
Labels: ✨ Feature, 🛠️ Fix, 📱 Layout
